name: branch-check
on:
  pull_request:
    branches:
      - main
    types: [opened, edited, reopened]
jobs:
  branch-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      - name: Check branch name
        run: |
          if [[ "$GITHUB_HEAD_REF" == "dev" ]]; then
            echo "Merging from dev branch is allowed"
            exit 0
          else
            echo "Merging from branch other than dev is not allowed"
            exit 1
          fi