# tests the webpack bundle to make sure that it can be compiled without any errors every time someone pushes or PRs
name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build webpack bundle
        run: npm run build
